/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package randomPicker;

/**
 *
 * @author Rowan
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Random Student Generator");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private javax.swing.JPanel panel;
    public void setPanel(javax.swing.JPanel p){
        //remove panel
        if(panel!=null){
            remove(panel);
        }
        //add new panel
        panel=p;
        add(panel);
        panel.setVisible(true);
        //redraw the frame
        super.paintComponents(getGraphics());
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
